//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresyWlascicieli
    {
        public int IdAdresuWlasciciela { get; set; }
        public Nullable<int> IdWlasciciela { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public Nullable<int> IdRodzajuAdresu { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Adresy Adresy { get; set; }
        public virtual Akcje Akcje { get; set; }
        public virtual RodzajAdresu RodzajAdresu { get; set; }
        public virtual Wlasciciele Wlasciciele { get; set; }
    }
}
