//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresKontrahenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdresKontrahenta()
        {
            this.Faktury = new HashSet<Faktury>();
        }
    
        public int IdAdresuKontrahenta { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<int> IdRodzajuAdresu { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual Kontrahenci Kontrahenci { get; set; }
        public virtual RodzajAdresu RodzajAdresu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
    }
}
