//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budynki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budynki()
        {
            this.Lokale = new HashSet<Lokale>();
        }
    
        public int IdBudynku { get; set; }
        public string Kod { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Numer { get; set; }
        public Nullable<int> LiczbaKondygnacji { get; set; }
        public Nullable<int> LiczbaLokali { get; set; }
        public string RodzajBudynku { get; set; }
        public string TypBudynku { get; set; }
        public string NumerDzialki { get; set; }
        public string PowierzchniaUzytkowa { get; set; }
        public Nullable<int> IdJednostkiMiary { get; set; }
        public Nullable<System.DateTime> RokBudowy { get; set; }
        public Nullable<System.DateTime> DataOddania { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lokale> Lokale { get; set; }
    }
}
