//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czynsze
    {
        public int IdCzynszu { get; set; }
        public Nullable<int> IdWspolnotyMieszkaniowej { get; set; }
        public Nullable<int> IdLokalu { get; set; }
        public Nullable<int> IdWlasciciela { get; set; }
        public Nullable<int> IdOplaty { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<decimal> KwotaBrutto { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<decimal> KwotaNetto { get; set; }
        public Nullable<int> IdStawkiVat { get; set; }
        public Nullable<System.DateTime> OdKiedy { get; set; }
        public Nullable<System.DateTime> DoKiedy { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual Lokale Lokale { get; set; }
        public virtual Oplaty Oplaty { get; set; }
        public virtual StawkiVat StawkiVat { get; set; }
        public virtual Wlasciciele Wlasciciele { get; set; }
        public virtual WspolnotyMieszkaniowe WspolnotyMieszkaniowe { get; set; }
    }
}
