//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktury()
        {
            this.PozycjeFaktury = new HashSet<PozycjeFaktury>();
        }
    
        public int IdFaktury { get; set; }
        public string Numer { get; set; }
        public Nullable<int> IdAdresuKontrahenta { get; set; }
        public Nullable<int> IdWspolnotyMieszkaniowej { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<int> IdSposobuPlatnosci { get; set; }
        public Nullable<decimal> Rabat { get; set; }
        public Nullable<int> IdRachunkuBankowego { get; set; }
        public Nullable<System.DateTime> DataCzasZaksiegowania { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<decimal> Razem { get; set; }
        public Nullable<decimal> Zaplacono { get; set; }
        public Nullable<decimal> Pozostaje { get; set; }
    
        public virtual AdresKontrahenta AdresKontrahenta { get; set; }
        public virtual Akcje Akcje { get; set; }
        public virtual RachunkiBankowe RachunkiBankowe { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        public virtual WspolnotyMieszkaniowe WspolnotyMieszkaniowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeFaktury> PozycjeFaktury { get; set; }
    }
}
