//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokaleWspolnoty
    {
        public int IdLokaluWspolnoty { get; set; }
        public Nullable<int> IdWspolnotyMieszkaniowej { get; set; }
        public Nullable<int> IdLokalu { get; set; }
        public Nullable<int> IdWlasciciela { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual Lokale Lokale { get; set; }
        public virtual Wlasciciele Wlasciciele { get; set; }
        public virtual WspolnotyMieszkaniowe WspolnotyMieszkaniowe { get; set; }
    }
}
