//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lokale()
        {
            this.Czynsze = new HashSet<Czynsze>();
            this.LokaleWspolnoty = new HashSet<LokaleWspolnoty>();
        }
    
        public int IdLokalu { get; set; }
        public Nullable<int> IdBudynku { get; set; }
        public string Kod { get; set; }
        public Nullable<int> IdRodzajuLokalu { get; set; }
        public string Klatka { get; set; }
        public string NumerLokalu { get; set; }
        public Nullable<int> Kondygnacja { get; set; }
        public Nullable<decimal> Udzialy { get; set; }
        public Nullable<decimal> Powierzchnia { get; set; }
        public Nullable<int> IdJednostkiMiary { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual Budynki Budynki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czynsze> Czynsze { get; set; }
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        public virtual RodzajLokalu RodzajLokalu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LokaleWspolnoty> LokaleWspolnoty { get; set; }
    }
}
