//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjeFaktury
    {
        public int IdPozycjiFaktury { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public Nullable<int> IdUslugi { get; set; }
        public string Kod { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
        public Nullable<int> IdJednostkiMiary { get; set; }
        public Nullable<decimal> Rabat { get; set; }
        public Nullable<decimal> CenaBrutto { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<decimal> KwotaVat { get; set; }
        public Nullable<int> IdStawkiVat { get; set; }
        public Nullable<decimal> CenaNetto { get; set; }
    
        public virtual Akcje Akcje { get; set; }
        public virtual Faktury Faktury { get; set; }
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        public virtual StawkiVat StawkiVat { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
