//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WspolnotyMieszkaniowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WspolnotyMieszkaniowe()
        {
            this.Czynsze = new HashSet<Czynsze>();
            this.Faktury = new HashSet<Faktury>();
            this.LokaleWspolnoty = new HashSet<LokaleWspolnoty>();
        }
    
        public int IdWspolnotyMieszkaniowej { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public string Nip { get; set; }
        public string Regon { get; set; }
        public string Krs { get; set; }
        public Nullable<System.DateTime> DataPowstania { get; set; }
        public Nullable<System.DateTime> PoczatkowyRokKsiegowy { get; set; }
        public Nullable<System.DateTime> BiezacyRokKsiegowy { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdAkcji { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
    
        public virtual Adresy Adresy { get; set; }
        public virtual Akcje Akcje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czynsze> Czynsze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LokaleWspolnoty> LokaleWspolnoty { get; set; }
    }
}
